apiVersion: v1
kind: ConfigMap
metadata:
  name: load-atlas-config
  namespace: business
data:
  atlas.toml: |
    PRIMARY_ARWEAVE_GATEWAY = "https://arweave.net"

    [indexers]
    ao = true
    pi = false
    flp = true
    explorer = true
    mainnet = true
