apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-atlas
  namespace: business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-atlas
  template:
    metadata:
      labels:
        app: load-atlas
    spec:
      nodeSelector:
        prod-app-worker-group: apps
      containers:
        - name: load-atlas
          image: 157.180.8.39:7000/load-atlas:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          securityContext:
            runAsUser: 0
          env:
            - name: ATLAS_CONFIG
              value: /app/atlas.toml
          envFrom:
            - secretRef:
                name: load-atlas-secret
          volumeMounts:
            - name: atlas-config
              mountPath: /app/atlas.toml
              subPath: atlas.toml
              readOnly: true
      volumes:
        - name: atlas-config
          configMap:
            name: load-atlas-config
